# Generated by Django 2.2.28 on 2022-07-04 15:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='static/shop/img/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='coreshop.Category')),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('discount_price', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='static/shop/img/')),
                ('image1', models.ImageField(null=True, upload_to='static/shop/img/')),
                ('image2', models.ImageField(null=True, upload_to='static/shop/img/')),
                ('image3', models.ImageField(null=True, upload_to='static/shop/img/')),
                ('image4', models.ImageField(null=True, upload_to='static/shop/img/')),
                ('Category', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='coreshop.Category')),
                ('tags', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='coreshop.Tags')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreshop.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('ordered_date', models.DateField(default=datetime.datetime.today)),
                ('order_ordered', models.BooleanField(default=False)),
                ('order_shipped', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(blank=True, default='', max_length=50)),
                ('shipping_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='coreshop.OrderItem')),
            ],
        ),
    ]
