# Generated by Django 2.2.28 on 2022-07-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreshop', '0002_checkoutaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
