# Generated by Django 2.2.28 on 2022-07-04 15:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreshop', '0003_auto_20220704_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckoutAddress',
            new_name='BillingAddress',
        ),
    ]
