# Generated by Django 2.2.28 on 2022-07-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreshop', '0004_auto_20220704_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
